### PR TITLE
Fix legacy calendar URLs defined by the `calendar_id`

### LINKED ISSUE #127: implement legacy calendar route
```
http://events.unl.edu/?calendar_id=1881
```

This route is being used by the 'live calendar' link in the manager interface and it should take you to the calendar home page for the given ID.

### PR DESCRIPTION
**Pull request by mfairchild365**
Allow determining the current calendar by the presence of `calendar_id`
Fixes #127

### CODE REVIEW

File: src/UNL/UCBCN/Frontend/Controller.php [hunk 1]
```diff
@@ -139,7 +139,9 @@ protected function determineCalendar()
         if (!empty($this->options['calendar_shortname'])) {
             // Try and get by shortname
             $this->options['calendar'] = Calendar::getByShortName($this->options['calendar_shortname']);
-        } else {
+        } else if (!empty($this->options['calendar_id'])) {
+            $this->options['calendar'] = Calendar::getByID($this->options['calendar_id']);
+        }else {
```
Comment (kabel) [inline src/UNL/UCBCN/Frontend/Controller.php]: Whitespace after `}` please.

Comment (mfairchild365) [inline src/UNL/UCBCN/Frontend/Controller.php]: Fixed in https://github.com/mfairchild365/UNL_UCBCN_Frontend/commit/7081c3f5f3ff2ab0df2db337d45b0db6da1e4a70
